security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000 # 1 hora em ms
    secret: ${JWT_SECRET:my-secret-key}
spring:
  application: 
    name: sistema-adocao-pets
  datasource:
    url: jdbc:postgresql://localhost:5432/ongdoacoes
    username: postgres 
    password: 1234
    driver-class-name: org.postgresql.Driver
    sql:
      init:
        mode: always
    flyway:
      baseline-on-migrate=true:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    repair=true: