security:
  jwt:
    token:
      expire-length: 3600000 # 1 hora em ms
    secret: ${JWT_SECRET:my-secret-key}

spring:
  application:
    name: sistema-adocao-pets

  datasource:
    url: jdbc:postgresql://localhost:5432/ongadocoes
    username: postgres
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    repair: true
    clean-disabled: false

  cors:
    originPatterns: http://localhost:3000
