CREATE TABLE IF NOT EXISTS usuario (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) UNIQUE NOT NULL,
    cell VARCHAR(15) UNIQUE NOT NULL,
    nome_usuario VARCHAR(255) UNIQUE NOT NULL,
    foto_perfil VARCHAR(255),
    role SMALLINT DEFAULT 1 NOT NULL
);