INSERT INTO
    ong (
        nome,
        email,
        senha,
        cnpj,
        responsavel,
        cell,
        nome_usuario,
        endereco,
        foto_perfil,
        descricao,
        site,
        role
    )
VALUES
    (
        'Ong 1',
        'ong1@example.com',
        'senha123',
        '53.696.807/0001-77',
        'Responsavel 1',
        '(11) 98765-4321',
        'NomeOng1',
        '{"logradouro":"Rua das Flores","numero":"100","complemento":"","bairro":"Jardim Paulista","cidade":"São Paulo","estado":"SP","cep":"01426030"}',
        'https://exemplo.com/fotos/ong1.jpg',
        'ONG focada em resgate de cães abandonados.',
        '{"site": "", "instagram": "", "facebook": "", "tiktok": "", "youtube": "", "whatsapp": "", "x": "", "linkedin": ""}',
        2
    ),
    (
        'Ong 2',
        'ong2@example.com',
        'senha123',
        '13.416.048/0001-27',
        'Responsavel 2',
        '(11) 98765-4322',
        'NomeOng2',
        '{"logradouro":"Avenida Brasil","numero":"500","complemento":"Sala 2","bairro":"Centro","cidade":"Rio de Janeiro","estado":"RJ","cep":"20000000"}',
        'https://exemplo.com/fotos/ong2.jpg',
        'ONG voltada à adoção de gatos e campanhas educativas.',
        '{"site": "", "instagram": "", "facebook": "", "tiktok": "", "youtube": "", "whatsapp": "", "x": "", "linkedin": ""}',
        2
    ),
    (
        'Ong 3',
        'ong3@example.com',
        'senha123',
        '87.051.353/0001-07',
        'Responsavel 3',
        '(11) 98765-4323',
        'NomeOng3',
        '{"logradouro":"Rua XV de Novembro","numero":"1234","complemento":"Fundos","bairro":"Liberdade","cidade":"Curitiba","estado":"PR","cep":"80020900"}',
        'https://exemplo.com/fotos/ong3.jpg',
        'Trabalha com reabilitação de animais vítimas de maus-tratos.',
        '{"site": "", "instagram": "", "facebook": "", "tiktok": "", "youtube": "", "whatsapp": "", "x": "", "linkedin": ""}',
        2
    ),
    (
        'Ong 4',
        'ong4@example.com',
        'senha123',
        '11.661.062/0001-60',
        'Responsavel 4',
        '(11) 98765-4324',
        'NomeOng4',
        '{"logradouro":"Rua Dom Pedro II","numero":"876","complemento":"","bairro":"Boa Vista","cidade":"Recife","estado":"PE","cep":"50720000"}',
        'https://exemplo.com/fotos/ong4.jpg',
        'ONG localizada no Nordeste com foco em educação ambiental.',
        '{"site": "", "instagram": "", "facebook": "", "tiktok": "", "youtube": "", "whatsapp": "", "x": "", "linkedin": ""}',
        2
    ),
    (
        'Ong 5',
        'ong5@example.com',
        'senha123',
        '25.188.312/0001-00',
        'Responsavel 5',
        '(11) 98765-4325',
        'NomeOng5',
        '{"logradouro":"Rua Barão do Rio Branco","numero":"45","complemento":"Andar superior","bairro":"Centro Histórico","cidade":"Porto Alegre","estado":"RS","cep":"90020000"}',
        'https://exemplo.com/fotos/ong5.jpg',
        'Foco em castração e vacinação de animais comunitários.',
        '{"site": "", "instagram": "", "facebook": "", "tiktok": "", "youtube": "", "whatsapp": "", "x": "", "linkedin": ""}',
        2
    );